AIBStore.Web/Controllers/AdminController.cs
//---------------------------------------------------------------------
// <copyright file="AdminController.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
//     THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
//     OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
//     LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR
//     FITNESS FOR A PARTICULAR PURPOSE.
// </copyright>
//---------------------------------------------------------------------
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AIBStore.Domain.Abstract;
using AIBStore.Domain.Entities;
using AIBStore.MVC.Helpers;
using AIBStore.MVC.Models;
using AIBStore.Domain.Concrete;
using AIBStore.Cache;

namespace AIBStore.MVC.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IUnitOfWork unitOfWork;

        public AdminController(UnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public ViewResult Index(LoginViewModel model)
        {
            try
            {
                string key = string.Concat(HttpContext.Session[Constants.Constants.SessionCacheKey], Constants.Constants.UsernameCacheKey);
                string userName = RedisUpdateHelper.Get<string>((string)(key));
                ViewBag.UserName = userName;
                return View(unitOfWork.ProductRepository().Get());
            }
            catch(Exception ex)
            {
                CustomError.HandleError(ex);
                return View("../Error/Error");
            }
        }

        public ViewResult Edit(int productId)
        {
            try
            {
                Product product = unitOfWork.ProductRepository().Get().FirstOrDefault(p => p.ProductID == productId);
                PopulateCategoryDropDownList(product.ProductCategory.ProductCategoryID);
                return View(product);
            }
            catch(Exception ex)
            {
                CustomError.HandleError(ex);
                return View("../Error/Error");
            }
        }

        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase image = null)
        {
            try
            { 
                if (ModelState.IsValid)
                {
                    if (image != null)
                    {
                        product.ImageMimeType = image.ContentType;
                        product.ImageData = new byte[image.ContentLength];
                        image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                    }
                    if (product.ProductID == 0)
                        unitOfWork.ProductRepository().Insert(product);
                    else
                        unitOfWork.ProductRepository().Update(product);
                    unitOfWork.Save();

                    TempData["message"] = string.Format("{0} has been saved", product.Name);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(product);
                }
            }
            catch(Exception ex)
            {
                CustomError.HandleError(ex);
                return View("../Error/Error");
            }
        }

        public ViewResult Create()
        {
            PopulateCategoryDropDownList();
            return View("Edit", new Product());
        }

        [HttpPost]
        public ActionResult Delete(int productId)
        {
            Product deletedProduct = unitOfWork.ProductRepository().Delete(productId);
            if (deletedProduct != null)
            {
                TempData["message"] = string.Format("{0} was deleted",
                    deletedProduct.Name);
            }
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            unitOfWork.Dispose();
            base.Dispose(disposing);
        }

        private void PopulateCategoryDropDownList(object selectedCategory = null)
        {
            var query = unitOfWork.ProductCategoryRepository().Get().OrderBy(x => x.Name);
            ViewBag.ProductCategoryID = new SelectList(query, "ProductCategoryID", "Name", selectedCategory);
        }
    }
}

AIBStore.Web/Controllers/ProductController.cs
//---------------------------------------------------------------------
// <copyright file="ProductController.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
//     THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
//     OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
//     LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR
//     FITNESS FOR A PARTICULAR PURPOSE.
// </copyright>
//---------------------------------------------------------------------using System.Web.Mvc;
using System.Linq;
using System.Web.Mvc;
using AIBStore.Domain.Abstract;
using AIBStore.Domain.Concrete;
using AIBStore.MVC.Models;
using AIBStore.Domain.Entities;
using System;
using AIBStore.MVC.Helpers;
using System.Configuration;

namespace AIBStore.MVC.Controllers
{
    public class ProductController : Controller
    {
        public int PageSize = 4;
        private IUnitOfWork unitOfWork;

        public ProductController(UnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
            try { PageSize = Convert.ToInt16(ConfigurationManager.AppSettings["PageSize"]); }
            catch (Exception) { PageSize = 4; }
        }

        public ViewResult List(string category, int pageNo = 1)
        {
            try
            {
                ProductsListViewModel model = new ProductsListViewModel
                {
                    Products = unitOfWork.ProductRepository().Get()
                    .Where(p => category == null || p.ProductCategory.Name.ToUpper() == category.ToUpper())
                    .OrderBy(p => p.ProductID)
                    .Skip((pageNo - 1) * PageSize)
                    .Take(PageSize),
                    PageInfo = new PageInfo
                    {
                        CurrentPage = pageNo,
                        ItemsOnPage = PageSize,
                        TotalNoItems = category == null ?
                            unitOfWork.ProductRepository().Get().Count() :
                            unitOfWork.ProductRepository().Get().Where(e => e.ProductCategory.Name == category).Count()
                    },
                    CurrCategory = category
                };
                return View(model);
            }
            catch(Exception ex)
            {
                CustomError.HandleError(ex);
                return View("../Error/Error");
            }
        }

        public FileContentResult GetImage(int productId)
        {
            Product prod = unitOfWork.ProductRepository().Get()
                .FirstOrDefault(p => p.ProductID == productId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        protected override void Dispose(bool disposing)
        {
            unitOfWork.Dispose();
            base.Dispose(disposing);
        }

    }
}

AIBStore.Web/Views/Admin/Edit - Copy (2).cshtml
@model AIBStore.Domain.Entities.Product

@{
    ViewBag.Title = "Admin: Edit " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Edit @Model.Name</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin",
                FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div class="panel-body">
            @Html.HiddenFor(m => m.ProductID)
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.Name, null, new { @class = "form-control" })
                @Html.ValidationMessage(Model.Name)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.Description, null, new { @class = "form-control", rows = 5 })
                @Html.ValidationMessage(Model.Description)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.Price, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Price)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ProductCategory, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DropDownListFor(model => model.ProductCategory, ViewBag.ProductCategory as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductCategory)
            </div>

            <div class="form-group">
                <div style="position:relative;">
                    <label>Image</label>
                    <a class='btn' href='javascript:;'>
                        Choose File...
                        <input type="file" name="Image" size="40"
                               style="position:absolute;z-index:2;top:0;
                            left:0;filter: alpha(opacity=0); opacity:0;
                            background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-static">No Image</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150"
                         src="@Url.Action("GetImage", "Product",
                        new { Model.ProductID })" />
                }
            </div>
        </div>

        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List", "Index", null, new
       {
           @class = "btn btn-default"
       })
        </div>
    }
</div>

AIBStore.Web/Views/Admin/Edit - Copy.cshtml
@model AIBStore.Domain.Entities.Product

@{
    ViewBag.Title = "Admin: Edit " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Edit @Model.Name</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin",
                FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div class="panel-body">
            @Html.HiddenFor(m => m.ProductID)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "ProductID":
                    case "ImageData":
                    case "ImageMimeType":
                        // do nothing
                        break;
                    default:
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @if (property.PropertyName == "Description")
                            {
                                @Html.TextArea(property.PropertyName, null,
                                new { @class = "form-control", rows = 5 })
                            }
                            else if (property.PropertyName == "ProductCategory")
                            {
                                @Html.DropDownList("ProductCategory", null, htmlAttributes: new { @class = "form-control" })
                            }
                            else
                            {
                                @Html.TextBox(property.PropertyName, null,
                                new { @class = "form-control" })
                            }
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }
            }

            <div class="form-group">
                <div style="position:relative;">
                    <label>Image</label>
                    <a class='btn' href='javascript:;'>
                        Choose File...
                        <input type="file" name="Image" size="40"
                               style="position:absolute;z-index:2;top:0;
                            left:0;filter: alpha(opacity=0); opacity:0;
                            background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-static">No Image</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150"
                         src="@Url.Action("GetImage", "Product",
                        new { Model.ProductID })" />
                }
            </div>
        </div>

        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List", "Index", null, new
       {
           @class = "btn btn-default"
       })
        </div>
    }
</div>

AIBStore.Web/Views/Admin/Edit.cshtml
@model AIBStore.Domain.Entities.Product

@{
    ViewBag.Title = "Admin: Edit " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Edit @Model.Name</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin",
                        FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div class="panel-body">
            @Html.HiddenFor(m => m.ProductID)
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.Name, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.Description, null, new { @class = "form-control", rows = 5 })
                @Html.ValidationMessageFor(model => model.Description)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.Price, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Price)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ProductCategory, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DropDownListFor(model => model.ProductCategoryID, ViewBag.ProductCategoryID as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductCategory)
            </div>
            <div class="form-group">
                <div style="position:relative;">
                    <label>Image</label>
                    <a class='btn' href='javascript:;'>
                        Choose File...
                        <input type="file" name="Image" size="40"
                               style="position:absolute;z-index:2;top:0;
                            left:0;filter: alpha(opacity=0); opacity:0;
                            background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-static">No Image</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150"
                         src="@Url.Action("GetImage", "Product",
                        new { Model.ProductID })" />
                }
            </div>
           
        </div>

        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List", "Index", null, new
       {
           @class = "btn btn-default"
       })
        </div>
    }
</div>

AIBStore.Web/Views/Admin/Index.cshtml
@model IEnumerable<AIBStore.Domain.Entities.Product>


@{
    ViewBag.Title = "Admin: All Products";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="navbar-right">
    @Html.ActionLink("Logout", "Logout", "Account", null,
        new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-text navbar-right">
    <b>Welcome:</b>
    @ViewBag.UserName
</div>

<div class="panel panel-default">

    <div class="panel-heading">
        <h3>Product List</h3>
    </div>

    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Name</th>
                <th class="text-left">Description</th>
                <th class="text-right">Price</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.ProductID</td>
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductID })</td>
                    <td class="text-leftt">@item.Description</td>
                    <td class="text-right">@item.Price.ToString("c")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("ProductID", item.ProductID)
                            <input type="submit"
                                   class="btn btn-default btn-xs"
                                   value="Delete" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add a new product", "Create", null,
            new { @class = "btn btn-default" })
    </div>
</div>